version: '3.9'
services:
  mongo:
    image: mongo:6
    container_name: physio-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  api:
    build: .
    container_name: physio-api
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - MONGO_URI=mongodb://mongo:27017/physio_db
    ports:
      - "4000:4000"
    depends_on:
      - mongo
volumes:
  mongo_data:

